mpi2/webapp-impc-production-tracker

src/app/registration-form/registration-form.component.ts

* Update call to user register endpoint.

Add-validations-to-User-Registration

---

src/app/app.module.ts
src/app/project/phenotype-plan-detail/phenotype-plan-detail.component.html
src/app/project/phenotype-plan-detail/phenotype-plan-detail.component.ts
src/app/project/production-plan-detail/production-plan-detail.component.html
src/app/project/production-plan-detail/production-plan-detail.component.ts
src/app/registration-form/registration-form.component.html
src/app/registration-form/registration-form.component.ts

project-view

---

src/app/_models/project/production_plan/crisprAttempt.ts
src/app/_services/project.service.ts
src/app/app.module.ts
src/app/project/production-plan-detail/production-plan-detail.component.html
src/app/project/production-plan-detail/production-plan-detail.component.ts
src/app/shared/confirmation/confirmation.component.html
src/app/shared/confirmation/confirmation.component.spec.ts
src/app/shared/confirmation/confirmation.component.ts

* Add table with information about Mutagenesis Donors, with links to delete them as well.

mutagenesisDonors

---

src/app/_models/index.ts
src/app/_models/project/projectDetails.ts
src/app/project/phenotype-plan-detail/phenotype-plan-detail.component.html
src/app/project/phenotype-plan-detail/phenotype-plan-detail.component.ts
src/app/project/production-plan-detail/production-plan-detail.component.html
src/app/project/production-plan-detail/production-plan-detail.component.ts
src/app/project/project-detail/project-detail.component.html
src/app/project/projects/projects.component.html
src/app/shared/confirmation/confirmation.component.html

* Fixed intentions so they are related with the intended gene.

intentions

---

src/app/_models/project/planDetails.ts
src/app/_models/project/projectSummary.ts
src/app/gene-search/gene-search.component.ts
src/app/project/projects/projects.component.html
src/app/project/projects/projects.component.ts

* Add the workgroup to the projects view. Changed order so production plans go first than phenotype plans.

workGroupInProjectsView

---

src/app/_models/project/phenotype_plan/phenotypePlan.ts
src/app/_models/project/project.ts
src/app/project/phenotype-plan-detail/phenotype-plan-detail.component.html
src/app/project/projects/projects.component.html

* Add initial information for phenotype plan.

phenotypeInfo

---

src/app/_services/project.service.ts
src/app/gene-search/gene-search.component.html

* Fix gen search page so marker symbol info is displayed

fixMarkerSymbol_intentionColumns

---

src/app/_models/workGroup.ts
src/app/_models/workUnit.ts
src/app/_services/project.service.ts
src/app/gene-search/gene-search.component.html
src/app/gene-search/gene-search.component.ts
src/app/project/projects/projects.component.html
src/app/project/projects/projects.component.ts

* Add capability to search applying filters.

searchComponent

---

src/app/_models/project/projectSummary.ts

* Change the plan info label information to include workGroup instead consortium.

planInfoLabel

---

src/app/_helpers/bearer-token-auth.interceptor.ts
src/app/project/projects/projects.component.ts

* Filters using the WorkUnit of the user for the projects view

FilteringProjectsByDefault

---

angular.json
package-lock.json
package.json
src/app/_services/authentication.service.ts
src/app/_services/configuration.service.ts
src/app/_services/project.service.ts
src/app/app.module.ts
src/app/gene-search/gene-search.component.ts
src/app/login/login.component.ts
src/app/project/projects/projects.component.html
src/app/project/projects/projects.component.ts

* Adds filtering to projects view

Filtering Projects

---

src/app/core/guards/auth.guard.ts
src/app/projects/projects-routing.module.ts
src/index.html

Add guard to control access to Projecs page.

Add guard to Project page

---

src/app/_helpers/error.interceptor.ts
src/app/genes/gene-search/gene-search.component.html
src/app/genes/gene-search/gene-search.component.ts
src/app/projects/components/create-project/create-project.component.html
src/app/projects/components/create-project/create-project.component.ts
src/app/projects/components/project-list/project-list.component.html
src/app/projects/components/project-list/project-list.component.ts

* Adding error divs to main components so when there is an error in the app the message is shown properly to the user.

Improving error management

---

src/app/admin/dashboard/dashboard.component.ts
src/app/core/guards/auth.guard.ts
src/app/core/services/basic-data.service.ts
src/app/core/services/permissions.service.ts
src/app/projects/components/create-project/create-project.component.ts
src/app/projects/components/phenotype-plan-detail/phenotype-plan-detail.component.html
src/app/projects/components/phenotype-plan-detail/phenotype-plan-detail.component.ts
src/app/projects/components/plan-details/plan-details.component.html
src/app/projects/components/plan-details/plan-details.component.spec.ts
src/app/projects/components/plan-details/plan-details.component.ts
src/app/projects/components/plan-history/plan-history.component.ts
src/app/projects/components/project-detail/project-detail.component.ts
src/app/projects/model/plan-details.ts
src/app/projects/model/project.ts
src/app/projects/projects.module.ts
src/app/projects/services/project.service.ts

Checking permissions to edit plan.

Add permissions to edit plan

---

src/app/core/model/changes-history.ts
src/app/core/services/basic-data.service.ts
src/app/core/services/configuration-data.service.ts
src/app/core/services/logged-user.service.ts
src/app/home/home.component.ts
src/app/plans/components/crispr-attempt/crispr-attempt.component.css
src/app/plans/components/crispr-attempt/crispr-attempt.component.html
src/app/plans/components/crispr-attempt/crispr-attempt.component.spec.ts
src/app/plans/components/crispr-attempt/crispr-attempt.component.ts
src/app/plans/components/plan-details/plan-details.component.html
src/app/plans/components/plan-details/plan-details.component.ts
src/app/plans/components/plan-summary/plan-summary.component.html
src/app/plans/components/production-plan/production-plan.component.html
src/app/plans/components/production-plan/production-plan.component.ts
src/app/plans/model/plan-details.ts
src/app/plans/model/plan.ts
src/app/plans/model/production-plan.ts
src/app/plans/plans.module.ts
src/app/plans/services/plan.service.ts
src/app/projects/components/project-detail/project-detail.component.html
src/app/projects/components/project-detail/project-detail.component.ts
src/app/shared/components/go-back/go-back.component.html
src/app/shared/components/go-back/go-back.component.spec.ts
src/app/shared/components/go-back/go-back.component.ts
src/app/shared/components/history/history.component.css
src/app/shared/components/history/history.component.html
src/app/shared/components/history/history.component.ts
src/app/shared/shared.module.ts

* First changes to update a plan using the UI.
* Changed from sessionStorage to localStorage to keep the login data when opening a new tab.
* Create a CrisprAttempt component to improve structure of the code.
* Added a GoBack component to be used in several parts of the application.
* Changed structure in HistoryComponent table to show the property changed in a separated column than the data changed.

Updating plan from UI

---

src/app/attempts/components/crispr/crispr-attempt-details/crispr-attempt-details.component.html
src/app/core/model/changes-history.ts

* Parse the propertyName in the history component so it is easier to read.

Parsing of action in history component

---

src/app/core/model/history/changes-history.ts
src/app/shared/components/history/history.component.html
src/app/shared/components/history/history.component.ts

* Updates History component due to changes in the api.

Update History structure

---

src/app/feature-modules/attempts/attempts.module.ts
src/app/feature-modules/attempts/components/crispr/crispr-attempt/crispr-attempt.component.html
src/app/feature-modules/attempts/components/crispr/mutagenesis-donors/mutagenesis-donors.component.html
src/app/feature-modules/attempts/components/crispr/mutagenesis-donors/mutagenesis-donors.component.spec.ts
src/app/feature-modules/attempts/components/crispr/mutagenesis-donors/mutagenesis-donors.component.ts

Extracted Mutagenesis Donors as independent component.

Extracted Mutagenesis Donors as independent component.

---

src/app/feature-modules/attempts/components/crispr/crispr-attempt-details/crispr-attempt-details.component.css
src/app/feature-modules/attempts/components/crispr/mutagenesis-details/mutagenesis-details.component.css
src/app/feature-modules/attempts/components/crispr/mutagenesis-donors/mutagenesis-donors.component.css
src/app/feature-modules/plans/components/plan-details/plan-details.component.css
src/app/shared/components/history/history.component.css
src/app/shared/components/history/history.component.html

* Adjusting History component to use Angular material
* Adjusting css from other components so the spaces between rows in tables make it easier to read the information.

Angular Material in History component

---

src/app/feature-modules/attempts/attempts.module.ts
src/app/feature-modules/attempts/components/crispr/crispr-attempt/crispr-attempt.component.html
src/app/feature-modules/attempts/components/crispr/genotype-primers/genotype-primers.component.css
src/app/feature-modules/attempts/components/crispr/guides/guides.component.css
src/app/feature-modules/attempts/components/crispr/guides/guides.component.html
src/app/feature-modules/attempts/components/crispr/guides/guides.component.spec.ts
src/app/feature-modules/attempts/components/crispr/guides/guides.component.ts
src/app/feature-modules/attempts/model/crispr/crispr-attempt.ts
src/app/feature-modules/attempts/model/crispr/guide.spec.ts
src/app/feature-modules/attempts/model/crispr/guide.ts

* Add Guide component that will be displayed as part of the Crispr Attempt component.

Add Guide Component

---

package-lock.json
package.json
src/app/app.component.html
src/app/feature-modules/projects/projects-routing.module.ts
styles.css

* Add package ng7-bootstrap-breadcrumb ^2.0.0 to have breadcrumbs.

Using breadcrumbs to Project, Plan and History pages

---

src/app/core/model/history/changes-history.ts
src/app/feature-modules/projects/components/project-detail/project-detail.component.html
src/app/feature-modules/projects/projects-routing.module.ts
src/app/feature-modules/projects/services/project.service.ts
src/app/shared/components/history/history.component.html
src/app/shared/components/history/history.component.ts

* Adjusted component to load history data from whatever entity is configured in the route using the data parameter.
* Add service to bring project history.
* Added link to visit the history page in a project.

Generalisation of history component.

---

src/app/core/helpers/fake-backend.interceptor.ts
src/app/core/model/conf/configuration-data.ts
src/app/feature-modules/attempts/attempts.module.ts
src/app/feature-modules/attempts/components/phenotyping/phenotyping-attempt/phenotyping-attempt.component.css
src/app/feature-modules/attempts/components/phenotyping/phenotyping-attempt/phenotyping-attempt.component.html
src/app/feature-modules/attempts/components/phenotyping/phenotyping-attempt/phenotyping-attempt.component.ts
src/app/feature-modules/attempts/components/phenotyping/tissue-distribution-centre/tissue-distribution-centre.component.css
src/app/feature-modules/attempts/components/phenotyping/tissue-distribution-centre/tissue-distribution-centre.component.html
src/app/feature-modules/attempts/components/phenotyping/tissue-distribution-centre/tissue-distribution-centre.component.spec.ts
src/app/feature-modules/attempts/components/phenotyping/tissue-distribution-centre/tissue-distribution-centre.component.ts
src/app/feature-modules/attempts/model/phenotyping/phenotyping_attempt.ts
src/app/feature-modules/projects/projects-routing.module.ts
src/app/shared/components/delete-confirmation/delete-confirmation.component.html
src/app/shared/components/delete-confirmation/delete-confirmation.component.spec.ts
src/app/shared/components/delete-confirmation/delete-confirmation.component.ts
src/app/shared/shared.module.ts

Add basic phenotyping attempt information.
Add Tissue Distribution Centre.
Add generic component to confirm before deleting elements.

Add Phenotyping Attempt component

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/core/guards/auth.guard.ts
src/app/core/helpers/error-interceptor.ts
src/app/core/helpers/fake-backend.interceptor.ts
src/app/core/services/logged-user.service.ts
src/app/core/services/permissions.service.ts
src/app/core/services/user.service.ts
src/app/feature-modules/attempts/components/phenotyping/tissue-distribution-centre/tissue-distribution-centre.component.ts
src/app/feature-modules/attempts/components/production/crispr/crispr-attempt-details/crispr-attempt-details.component.html
src/app/feature-modules/attempts/components/production/crispr/crispr-attempt-details/crispr-attempt-details.component.ts
src/app/feature-modules/attempts/components/production/crispr/crispr-attempt/crispr-attempt.component.html
src/app/feature-modules/attempts/components/production/crispr/crispr-attempt/crispr-attempt.component.ts
src/app/feature-modules/attempts/components/production/crispr/guides/guides.component.ts
src/app/feature-modules/attempts/model/production/crispr/crispr-attempt.ts
src/app/feature-modules/genes/gene-search/gene-search.component.ts
src/app/feature-modules/plans/components/phenotyping-plan/phenotyping-plan.component.html
src/app/feature-modules/plans/components/plan-details/plan-details.component.html
src/app/feature-modules/plans/components/plan-details/plan-details.component.ts
src/app/feature-modules/plans/components/plan-summary/plan-summary.component.html
src/app/feature-modules/plans/components/production-plan/production-plan.component.html
src/app/feature-modules/plans/components/production-plan/production-plan.component.ts
src/app/feature-modules/plans/model/plan-details.ts
src/app/feature-modules/plans/model/plan.ts
src/app/feature-modules/plans/services/plan.service.ts
src/app/feature-modules/projects/components/project-detail/project-detail.component.html
src/app/feature-modules/projects/components/project-detail/project-detail.component.ts
src/app/feature-modules/projects/model/project.ts

* Moving privacy from plan to project.
* Validating that an object has changed before updating it.
* Removing event emitters from children in plan component as the verification of change is done now comparing the jsons of both the original and new plan.
* Removing several console.log

Adjusting project and plan view

---

src/app/core/services/message.service.ts
src/app/feature-modules/attempts/components/production/crispr/genotype-primers/genotype-primers.component.css
src/app/feature-modules/attempts/components/production/crispr/genotype-primers/genotype-primers.component.html
src/app/feature-modules/attempts/components/production/crispr/genotype-primers/genotype-primers.component.ts
src/app/feature-modules/attempts/components/production/crispr/guides/guides.component.css
src/app/feature-modules/attempts/components/production/crispr/guides/guides.component.ts
src/app/feature-modules/attempts/components/production/crispr/mutagenesis-donors/mutagenesis-donors.component.html
src/app/feature-modules/attempts/model/production/crispr/crispr-attempt.ts
src/app/feature-modules/plans/components/phenotyping-plan/phenotyping-plan.component.ts
src/app/feature-modules/plans/components/production-plan/production-plan.component.ts
src/app/feature-modules/plans/services/plan.service.ts
src/app/shared/components/delete-confirmation/delete-confirmation.component.html
src/app/shared/directives/digit-only.directive.ts
src/app/shared/shared.module.ts

* Validation of nulls.
* Deletion after confirmation in old values.
* Edition status.

Make Genotype Primers table editable

---

src/app/core/services/configuration-data.service.ts
src/app/core/services/logged-user.service.ts
src/app/core/services/permissions.service.ts
src/app/feature-modules/plans/components/phenotyping-plan/phenotyping-plan.component.ts
src/app/feature-modules/plans/components/plan-details/plan-details.component.ts
src/app/feature-modules/plans/components/production-plan/production-plan.component.ts
src/app/feature-modules/projects/components/project-detail/project-detail.component.ts

* If there is not logged user into the system, automatically the permissions to edit are set as false.

Checking permissions only if a user is logged into the system.

---

src/app/core/services/logged-user.service.ts
src/app/feature-modules/genes/gene-search/gene-search.component.ts
src/app/feature-modules/projects/components/project-list/project-list.component.html
src/app/feature-modules/projects/components/project-list/project-list.component.ts
src/app/feature-modules/projects/services/project.service.ts

* Includes also a fix in obtaining the appUrl that gets security information about the logged user.

Initial implementation of new filters in projects.

---

src/app/core/model/common/array-filter.ts
src/app/core/model/common/filter.ts
src/app/feature-modules/genes/gene-search/gene-search.component.ts
src/app/feature-modules/projects/components/project-list/project-list.component.html
src/app/feature-modules/projects/components/project-list/project-list.component.ts
src/app/feature-modules/projects/services/project-filter.service.ts
src/app/feature-modules/projects/services/project.service.ts

* Refactoring to create a class in charge of build the needed filters.

Adding filters to project: intention and privacy.

---

src/app/feature-modules/search/components/search/search.component.html
src/app/feature-modules/search/components/search/search.component.ts

Added a row saying that the search term does not have associated projects.

Including results for searches with not projects associated.

---

src/app/core/services/configuration-data.service.ts
src/app/feature-modules/search/components/search/search.component.ts
src/app/feature-modules/search/services/search.service.ts
src/app/shared/components/informative-dialog/informative-dialog.component.html
src/app/shared/components/informative-dialog/informative-dialog.component.spec.ts
src/app/shared/components/informative-dialog/informative-dialog.component.ts
src/app/shared/shared.module.ts

* Created InformativeDialog component to show generic messages to the user.
* Updated parameter search type to match update in api.

Added dialog to inform when a search is invalid.

---

src/app/feature-modules/projects/components/project-list/project-list.component.html
src/app/feature-modules/projects/model/project.ts
src/app/feature-modules/search/components/search/search.component.html
src/app/feature-modules/search/components/search/search.component.ts
src/app/feature-modules/search/model/search.result.ts

* Also added a Search Result Comments in Search to see information about the results like:
- There were no project associated to the search.
- The search term is actually a synonym.

Add Access Status column for Search and Projects

---

src/app/app.module.ts
src/app/feature-modules/genes/components/gene/gene.component.css
src/app/feature-modules/genes/components/gene/gene.component.html
src/app/feature-modules/genes/genes.module.ts
src/app/feature-modules/locations/components/location/location.component.css
src/app/feature-modules/locations/components/location/location.component.html
src/app/feature-modules/locations/components/location/location.component.ts
src/app/feature-modules/locations/locations.module.ts
src/app/feature-modules/locations/model/location.ts
src/app/feature-modules/projects/components/intention-by-gene/intention-by-gene.component.html
src/app/feature-modules/projects/components/intention-by-gene/intention-by-gene.component.ts
src/app/feature-modules/projects/components/intention-by-location/intention-by-location.component.css
src/app/feature-modules/projects/components/intention-by-location/intention-by-location.component.html
src/app/feature-modules/projects/components/intention-by-location/intention-by-location.component.spec.ts
src/app/feature-modules/projects/components/intention-by-location/intention-by-location.component.ts
src/app/feature-modules/projects/components/intentions/intentions.component.css
src/app/feature-modules/projects/components/intentions/intentions.component.html
src/app/feature-modules/projects/components/project-detail/project-detail.component.css
src/app/feature-modules/projects/components/project-detail/project-detail.component.html
src/app/feature-modules/projects/components/project-detail/project-detail.component.ts
src/app/feature-modules/projects/model/intention-by-location.ts
src/app/feature-modules/projects/projects.module.ts

* Changed also several tables to use divs instead.
* Using fxLayout to show the intentions (by gene or by location).

Added detailed information for Intention By Location

---

imits-theme.scss
src/app/core/model/user/user.ts
src/app/core/services/permissions.service.ts
src/app/feature-modules/admin/admin-routing.module.ts
src/app/feature-modules/admin/components/dashboard/dashboard.component.html
src/app/feature-modules/admin/components/user-registration/user-registration.component.html
src/app/feature-modules/admin/components/user-registration/user-registration.component.ts
src/app/feature-modules/projects/components/project-detail/project-detail.component.ts
styles.css

* First part of converting UserRegistrationComponent to a component that can also update the information of an existing user.
* Modified the scss style file to have the accent option as blue instead gray.

Making the UserRegistrationComponent more generic

---

src/app/core/components/header/header.component.html
src/app/feature-modules/projects/components/project-list/project-list.component.html
src/app/feature-modules/search/components/search/search.component.html
src/app/feature-modules/search/components/search/search.component.ts
src/app/model/bio/project.ts

* Includes removing unused menus.

Fixing search type to Gene

---

src/app/feature-modules/filters/components/filter-container/filter-container.component.html
src/app/feature-modules/filters/components/filter-container/filter-container.component.ts
src/app/feature-modules/projects/components/project-list-content/project-list-content.component.html
src/app/feature-modules/projects/components/project-list/project-list.component.ts
src/app/feature-modules/search/components/search/search.component.html
src/app/feature-modules/search/components/search/search.component.ts

Allow to clear filters. Changing order of filters in Projects view. Adding MGI to Search and Projects. Adding Best orthologs to Projects.

General improvements

---

src/app/core/services/authentication.service.spec.ts
src/app/core/services/config-asset-loader.service.spec.ts
src/app/core/services/configuration-data.service.spec.ts
src/app/core/services/funder.service.spec.ts
src/app/core/services/gene.service.spec.ts
src/app/core/services/logged-user.service.spec.ts
src/app/core/services/managed-lists.service.spec.ts
src/app/core/services/message.service.spec.ts
src/app/core/services/permissions.service.spec.ts
src/app/core/services/user.service.spec.ts
src/app/core/services/work-group.service.spec.ts
src/app/feature-modules/attempts/services/attempt-service.service.spec.ts
src/app/feature-modules/filters/services/filter.service.spec.ts
src/app/feature-modules/plans/services/plan.service.spec.ts
src/app/feature-modules/target-gene-list/services/target-gene-list.service.spec.ts

Ref: https://app.zenhub.com/workspaces/cda-5e26daa5fe6fac729f87218d/issues/mpi2/phenotypedata/299

Fix lint issues due to angular 9 migration

---

package-lock.json
package.json

Solving audit problem.
Using the following post to fix the minimist problem we were having. The current package has a vulnerability (prototype pollution), so this changes force to use a more recent version
https://stackoverflow.com/a/60994103/5440828

Fixing audit problems: Add resolution for minimist package

---

src/app/feature-modules/projects/components/project-list-content/project-list-content.component.html
src/app/feature-modules/search/components/search-content/search-content.component.html
src/app/feature-modules/search/components/search-content/search-content.component.ts
src/app/model/bio/project.ts

Add 'Summary Status' column to Search and Projects components.

Update Search UI

---

src/app/feature-modules/intentions/components/intention-list/intention-list.component.css
src/app/feature-modules/intentions/components/intention-list/intention-list.component.html
src/app/feature-modules/intentions/components/intention-list/intention-list.component.ts
src/app/feature-modules/intentions/components/sequence-intention-detail/sequence-intention-detail.component.css
src/app/feature-modules/intentions/components/sequence-intention-detail/sequence-intention-detail.component.html
src/app/feature-modules/intentions/components/sequence-intention-detail/sequence-intention-detail.component.spec.ts
src/app/feature-modules/intentions/components/sequence-intention-detail/sequence-intention-detail.component.ts
src/app/feature-modules/intentions/components/sequences-intentions-dialog/sequences-intentions-dialog.component.css
src/app/feature-modules/intentions/components/sequences-intentions-dialog/sequences-intentions-dialog.component.html
src/app/feature-modules/intentions/components/sequences-intentions-dialog/sequences-intentions-dialog.component.spec.ts
src/app/feature-modules/intentions/components/sequences-intentions-dialog/sequences-intentions-dialog.component.ts
src/app/feature-modules/intentions/intentions.module.ts
src/app/feature-modules/projects/components/project-detail/project-detail.component.ts
src/app/shared/shared.module.ts

-First implementation of project sequences.

Update Project detail view

---

src/app/core/model/history/changes-history.ts
src/app/core/model/history/history-detail.ts
src/app/shared/components/history/history.component.html

- Added columns field and  note to the table.
- Deleted column description.
- Filtered out changes type "Element changed"

Adapt History component to reflect changes in API

---

src/app/core/model/conf/configuration-data.ts
src/app/feature-modules/attempts/components/production/crispr/nuclease/nuclease.component.html
src/app/feature-modules/attempts/components/production/crispr/nuclease/nuclease.component.ts

Display correctly the nucleases information

Fix display issues in Production Plan

---

src/app/feature-modules/attempts/components/production/crispr/guides/guides.component.html
src/app/feature-modules/attempts/components/production/crispr/mutagenesis-details/mutagenesis-details.component.html
src/app/feature-modules/plans/model/plan.ts
src/app/feature-modules/projects/components/project-detail/project-detail.component.html
src/app/feature-modules/projects/components/project-detail/project-detail.component.ts
src/app/model/bio/project.ts
src/app/model/bio/status-date.ts

- Remove Recovery field from project.
- Fix Assignment Status Stamps in project.
- Put Intentions section before the comment in project.
- Fix display of "stop" and "truncate guide" in production plan.
- Remove "Protocol url" field from Mutagenesis details section.

Small changes to project view and plan production view

---

src/app/feature-modules/plans/components/production-plan/production-plan.component.html
src/app/feature-modules/plans/components/update-notification/update-notification.component.ts
src/app/feature-modules/plans/model/plan.ts
src/app/feature-modules/projects/components/project-detail/project-detail.component.ts
src/app/model/status_transition/status_transition.ts
src/app/model/status_transition/transition.ts
src/app/shared/components/status-transition/status-transition.component.css
src/app/shared/components/status-transition/status-transition.component.html
src/app/shared/components/status-transition/status-transition.component.spec.ts
src/app/shared/components/status-transition/status-transition.component.ts
src/app/shared/shared.module.ts

- Create Status Transition component.
- Added component to production plan view.

Create a Status transition components

---

src/app/app.module.ts
src/app/feature-modules/plans/components/outcomes/colony-detail/colony-detail.component.css
src/app/feature-modules/plans/components/outcomes/colony-detail/colony-detail.component.html
src/app/feature-modules/plans/components/outcomes/colony-detail/colony-detail.component.spec.ts
src/app/feature-modules/plans/components/outcomes/colony-detail/colony-detail.component.ts
src/app/feature-modules/plans/components/outcomes/outcome-detail/outcome-detail.component.css
src/app/feature-modules/plans/components/outcomes/outcome-detail/outcome-detail.component.html
src/app/feature-modules/plans/components/outcomes/outcome-detail/outcome-detail.component.spec.ts
src/app/feature-modules/plans/components/outcomes/outcome-detail/outcome-detail.component.ts
src/app/feature-modules/plans/components/outcomes/outcome-list/outcome-list.component.html
src/app/feature-modules/plans/components/outcomes/outcome-list/outcome-list.component.spec.ts
src/app/feature-modules/plans/components/outcomes/outcome-list/outcome-list.component.ts
src/app/feature-modules/plans/components/production-plan/production-plan.component.html
src/app/feature-modules/plans/components/production-plan/production-plan.component.ts
src/app/feature-modules/plans/model/outcomes/colony.ts
src/app/feature-modules/plans/model/outcomes/distribution-product.ts
src/app/feature-modules/plans/model/outcomes/outcome.ts
src/app/feature-modules/plans/model/outcomes/specimen.ts
src/app/feature-modules/plans/plans.module.ts
src/app/feature-modules/plans/services/outcome.service.ts
src/app/shared/components/status-transition/status-transition.component.ts

- Initial files to Outcomes section in plans.

Create Outcome component in Angular

---

src/app/feature-modules/plans/components/outcomes/colony-detail/colony-detail.component.css
src/app/feature-modules/plans/components/outcomes/colony-detail/colony-detail.component.html
src/app/feature-modules/plans/components/outcomes/mutation-detail/mutation-detail.component.html
src/app/feature-modules/plans/components/outcomes/mutation-detail/mutation-detail.component.ts
src/app/feature-modules/plans/components/outcomes/outcome-detail/outcome-detail.component.ts
src/app/shared/components/status-transition/status-transition.component.css
src/app/shared/components/status-transition/status-transition.component.html

- Allow edition of colony name, genotype comment and allele categories.
- Add status section to outcomes

Additional editions in outcomes details

---

src/app/feature-modules/plans/components/outcomes/colony-detail/colony-detail.component.css
src/app/feature-modules/plans/components/outcomes/colony-detail/colony-detail.component.html
src/app/feature-modules/plans/components/outcomes/mutation-detail/mutation-detail.component.css
src/app/feature-modules/plans/components/outcomes/mutation-detail/mutation-detail.component.html
src/app/feature-modules/plans/components/outcomes/mutation-detail/mutation-detail.component.ts
src/app/feature-modules/plans/components/outcomes/outcome-detail/outcome-detail.component.html
src/app/feature-modules/plans/plans.module.ts
src/app/feature-modules/sequences/components/indexed-sequence/indexed-sequence.component.html
src/app/feature-modules/sequences/components/indexed-sequence/indexed-sequence.component.spec.ts
src/app/feature-modules/sequences/components/indexed-sequence/indexed-sequence.component.ts
src/app/feature-modules/sequences/model/indexed-location.ts
src/app/feature-modules/sequences/model/indexed-sequence.ts
src/app/feature-modules/sequences/sequences.module.ts
src/app/shared/components/status-date/status-date.component.html
src/app/shared/components/status-transition/status-transition.component.html

- Rearrangement of several elements in the Outcome details page according to internal feedback

Internal UI feedback

---

imits-theme.scss
src/app/feature-modules/plans/components/outcomes/mutation-detail/mutation-detail.component.css
src/app/feature-modules/plans/components/outcomes/mutation-detail/mutation-detail.component.html
src/app/feature-modules/plans/components/outcomes/mutation-detail/mutation-detail.component.ts
src/app/feature-modules/plans/components/outcomes/outcome-detail/outcome-detail.component.css
src/app/feature-modules/plans/components/outcomes/outcome-detail/outcome-detail.component.html
src/app/feature-modules/plans/components/outcomes/outcome-detail/outcome-detail.component.ts
src/app/feature-modules/plans/model/outcomes/mutation.ts
src/app/feature-modules/sequences/components/indexed-sequence/indexed-sequence.component.css
src/app/feature-modules/sequences/components/indexed-sequence/indexed-sequence.component.html
src/app/feature-modules/sequences/components/indexed-sequence/indexed-sequence.component.ts
src/app/shared/components/autocomplete-gene/autocomplete-gene.component.ts

- Change color of delete buttons (warn color at .scss file.
- Moving position of delete buttons in mutation and sequence

Internal UI feedback changes

---

src/app/shared/components/delete-confirmation/delete-confirmation.component.html

- Change text in buttons to Ok and Cancel.

Change text in delete confirmation component

---

src/app/feature-modules/attempts/components/phenotyping/phenotyping-stage-details/phenotyping-stage-details.component.css
src/app/feature-modules/attempts/components/phenotyping/phenotyping-stage-details/phenotyping-stage-details.component.html
src/app/feature-modules/attempts/components/phenotyping/phenotyping-stage-details/phenotyping-stage-details.component.ts
src/app/feature-modules/attempts/components/phenotyping/tissue-distribution-centre/tissue-distribution-centre.component.css
src/app/feature-modules/attempts/components/phenotyping/tissue-distribution-centre/tissue-distribution-centre.component.html
src/app/feature-modules/attempts/components/phenotyping/tissue-distribution-centre/tissue-distribution-centre.component.ts
src/app/feature-modules/attempts/model/phenotyping/phenotyping_attempt.ts
src/app/feature-modules/plans/components/outcomes/qc-results/qc-results.component.ts
src/app/feature-modules/plans/services/phenotyping-stage.service.ts
src/app/feature-modules/projects/projects-routing.module.ts
src/app/shared/components/history/history.component.ts

- Style changes.
- Add functionality to edit information.
- Add history section.

Phenotyping stage

---

src/app/core/model/user/user.ts
src/app/core/services/user.service.ts
src/app/feature-modules/users/components/profile-editor/profile-editor.component.html
src/app/feature-modules/users/components/profile-editor/profile-editor.component.ts

- Allow to update contactable field.
- Allow to update password field.

Allow to update changes in own profile

---

src/app/feature-modules/attempts/model/phenotyping/phenotyping_starting_point.ts
src/app/feature-modules/plans/components/plan-creation/plan-creation.component.css
src/app/feature-modules/plans/components/plan-creation/plan-creation.component.html
src/app/feature-modules/plans/components/plan-creation/plan-creation.component.ts
src/app/feature-modules/projects/components/project-detail/project-detail.component.css
src/app/feature-modules/projects/components/project-detail/project-detail.component.html

- Show error section when plan creation fails.
- Add starting point for phenotyping plans
- Change display of plan summaries in project detail

UI improvements

---

src/app/core/model/conf/configuration-data.ts
src/app/feature-modules/plans/components/plan-creation/plan-creation.component.html
src/app/feature-modules/plans/components/plan-creation/plan-creation.component.ts

- Show work groups related with selected work unit.
- Show attempt types related with selected plan type.
- Show funders related with selected work group.

Filter possible values dropdowns while creating plans

---

src/app/feature-modules/attempts/components/production/crispr/guides/guides.component.css
src/app/feature-modules/attempts/components/production/crispr/guides/guides.component.html
src/app/feature-modules/attempts/components/production/crispr/guides/guides.component.ts

- Add some missing fields
- Making the table editable

Complete guides component

---

src/app/feature-modules/attempts/components/phenotyping/phenotyping-attempt-details/phenotyping-attempt-details.component.html
src/app/feature-modules/attempts/components/phenotyping/phenotyping-attempt-details/phenotyping-attempt-details.component.ts
src/app/feature-modules/attempts/components/phenotyping/phenotyping-stage-details/phenotyping-stage-details.component.html
src/app/feature-modules/attempts/model/phenotyping/phenotyping-stage.ts
src/app/feature-modules/attempts/model/phenotyping/phenotyping_attempt.ts

Move doNotCountTowardsCompleteness from phenotyping stage to phenotyping attempt

Move doNotCountTowardsCompleteness from phenotyping stage o phenotyping attempt

---

src/app/feature-modules/search/components/search-input/search-input.component.css
src/app/feature-modules/search/components/search-input/search-input.component.html

- Improve help texts in search box

UI improvements:

---

package-lock.json

Fixed vulnerability reported by npm audit

Updated vulnerability reported by npm audit

---

Dockerfile
package-lock.json
package.json

Update npm audit command in the Dockerfile to only check production dependencies.

---

src/app/feature-modules/attempts/components/production/cre-allele-modification/cre-allele-modification.component.css
src/app/feature-modules/attempts/components/production/cre-allele-modification/cre-allele-modification.component.html
src/app/feature-modules/attempts/components/production/crispr/assay/assay.component.html
src/app/feature-modules/attempts/components/production/crispr/assay/assay.component.ts
src/app/feature-modules/attempts/components/production/escell/escell-attempt.component.css
src/app/feature-modules/attempts/components/production/escell/escell-attempt.component.html
src/app/feature-modules/attempts/components/production/escell/escell-attempt.component.ts
src/app/feature-modules/plans/components/outcomes/colony-summary/colony-summary.component.css
src/app/feature-modules/plans/components/outcomes/colony-summary/colony-summary.component.html
src/app/feature-modules/plans/components/outcomes/colony-summary/colony-summary.component.ts
src/app/feature-modules/plans/components/outcomes/mutation-detail/mutation-detail.component.html
src/app/feature-modules/plans/components/outcomes/mutation-detail/mutation-detail.component.ts
src/app/feature-modules/plans/components/outcomes/outcome-detail/outcome-detail.component.html
src/app/feature-modules/plans/components/outcomes/outcome-detail/outcome-detail.component.ts
src/app/feature-modules/plans/components/outcomes/outcome-summary/outcome-summary.component.css
src/app/feature-modules/plans/components/outcomes/outcome-summary/outcome-summary.component.html
src/app/feature-modules/plans/components/outcomes/outcome-summary/outcome-summary.component.ts
src/app/feature-modules/plans/components/plan-details/plan-details.component.css
src/app/feature-modules/plans/components/plan-details/plan-details.component.html
src/app/feature-modules/projects/components/project-consortium-institutes/project-consortium-institutes.component.html
src/app/feature-modules/projects/components/project-consortium-institutes/project-consortium-institutes.component.ts
src/app/feature-modules/projects/components/project-creation/project-creation.component.html
src/app/feature-modules/projects/components/project-creation/project-creation.component.ts
src/app/feature-modules/projects/components/project-es-cell-qc/project-es-cell-qc/project-es-cell-qc.component.html
src/app/feature-modules/projects/components/project-intention/project-intention.component.html
src/app/feature-modules/projects/components/project-intention/project-intention.component.ts
src/app/shared/components/plan-creation/plan-creation.component.html
src/app/shared/components/plan-creation/plan-creation.component.ts

- Project Type => Project id in plan details.
- Project details => Set time out for showing project consortia when not log in.
- Project creation => Fix project intention bug when adding a new row.
- Project creation => Reduce the list of attempt type options.
- Assay results => No gene specified.
- ES Cell attempt form => when not log in, improve template.
- Project Creation => mutation categorisation only show alleleCategories.
- Project Creation => molecular mutation type not show legacy.

Fix templates

---

src/app/feature-modules/attempts/components/production/es-cell-allele-modification/es-cell-allele-modification-attempt.component.ts
src/app/feature-modules/attempts/components/production/escell/escell-attempt.component.html
src/app/feature-modules/attempts/components/production/escell/escell-attempt.component.ts
src/app/feature-modules/attempts/model/production/es-cell-allele-modification/es-cell-allele-modification-attempt.ts
src/app/feature-modules/attempts/model/production/escell/escell-attempt.ts
src/app/feature-modules/plans/components/production-plan/production-plan.component.html
src/app/feature-modules/plans/components/production-plan/production-plan.component.ts

Documentation update to include es cell and allele modification attempts information.

---

src/app/feature-modules/plans/components/production-plan/production-plan.component.ts

deleting all attempt objects when moving to the plan abandoned status (bug fix)

deleting all attempt objects when moving to the plan abandoned status

---

package-lock.json

update fix vulnerabilities

---

src/app/feature-modules/plans/components/production-plan/production-plan.component.ts
src/app/feature-modules/projects/components/project-detail/project-detail.component.ts

ES Cell Allele Modification Plans

---

package-lock.json
src/app/feature-modules/plans/components/production-plan/production-plan.component.ts
src/app/feature-modules/projects/components/project-detail/project-detail.component.ts

ES Cell Allele Modification Plans
json error fixed

ES Cell Allele Modification Plans json error fixed

---

src/app/feature-modules/plans/components/outcomes/mutation-detail/mutation-detail.component.html
src/app/feature-modules/plans/components/outcomes/mutation-detail/mutation-detail.component.ts

validating mutation symbol changes

validating mutation symbol changes

---

src/app/feature-modules/plans/components/production-plan/production-plan.component.ts
src/app/feature-modules/plans/services/plan.service.ts

validating sequence

---

src/app/feature-modules/plans/components/production-plan/production-plan.component.ts

error box showing optimized

---

src/app/core/components/reports/production-numbers-tab/production-numbers-tab.component.html
src/app/core/components/reports/production-numbers-tab/production-numbers-tab.component.ts
src/app/core/components/reports/reports.component.html

Disable work group autocomplete if user hasn't selected a work unit, filtering while typing in the autocomplete and moving some reports to a common tab.

Updates to Reports page

---

src/app/core/components/reports/production-numbers-tab/production-numbers-tab.component.html
src/app/core/components/reports/production-numbers-tab/production-numbers-tab.component.ts
src/app/core/components/reports/production-numbers-tab/production-numbers-tab.scss
src/app/core/components/reports/reports.component.html

Reports page - text updates and download functionality

---

imits-theme.scss
src/app/core/components/reports/production-numbers-tab/production-numbers-tab.component.html
src/app/core/components/reports/production-numbers-tab/production-numbers-tab.component.ts
src/app/core/components/reports/production-numbers-tab/production-numbers-tab.scss
src/app/core/components/reports/reports.component.html
src/app/core/core.module.ts

Tab styling and filter updates to reports page

---

src/app/feature-modules/attempts/components/production/crispr/guides/guides.component.html
src/app/feature-modules/plans/components/outcomes/distribution-product-list/distribution-product-list.component.html

distribution id disabled

---

src/app/core/components/footer/footer.component.html
src/app/core/components/footer/footer.component.ts

Display current year instead hardcoded "2020"

[Footer] - Add terms of use link

---

src/app/core/components/footer/footer.component.html
src/app/feature-modules/users/components/profile-editor/profile-editor.component.html

Update privacy notices
